# Dependencies
markdown:           kramdown
highlighter:        rouge

# Permalinks
permalink:          pretty

# Setup
title:              VcamX
description:        'Jiarong Wei'
url:                http://vcamx.me
baseurl:            /

author:
  name:             VcamX
  email:            vcamx3@gmail.com

social:
  facebook:         jiarong.wei
  googleplus:       JiarongWei
  _linkedin:        jiarongwei
  twitter:          VcamX
  weibo:            VcamX
  github:           VcamX

paginate:           5

excerpt_separator:  <!--more-->
