# Dependencies
markdown:           kramdown
highlighter:        rouge

# Permalinks
permalink:          pretty

# Setup
title:              VcamX
description:        'Jiarong Wei'
url:                http://vcamx.me

author:
  name:             VcamX
  email:            vcamx3@gmail.com

social:
  linkedin:         jiarongwei
  twitter:          VcamX
  github:           VcamX

paginate:           5

excerpt_separator:  <!--more-->

gems: [jekyll-paginate]

